---
extends: default
ignore:
  - tests
  - changelogs/changelog.yaml
  - plugins

level: warning

rules:
  braces:
    max-spaces-inside: 1
    level: warning
  comments:
    min-spaces-from-content: 1
    level: warning
  comments-indentation: false
  line-length:
    max: 160
    level: warning
  indentation:
    level: warning
  trailing-spaces:
    level: warning
  new-line-at-end-of-file:
    level: warning
  key-duplicates:
    level: warning
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
