---
namespace: cisco
name: ise
version: 3.0.0
readme: README.md
authors:
  - William Astorga <wastorga@cloverhound.cr>
  - Jose Bogarin <jbogarin@cloverhound.cr>
  - Francisco Munoz <fmunoz@cloverhound.cr>
  - Bryan Vargas <bvasquez@cloverhound.cr>
description: Ansible Modules for Cisco ISE
license_file: "LICENSE"
tags:
  - cisco
  - ise
  - cloud
  - collection
  - networking
  - sdn
dependencies:
  ansible.utils: ">=2.0.0,<7.0"
repository: https://github.com/CiscoISE/ansible-ise
documentation: https://ciscoise.github.io/ansible-ise/
homepage: https://github.com/CiscoISE/ansible-ise
issues: https://github.com/CiscoISE/ansible-ise/issues
