---
namespace: cisco
name: ise
version: 0.0.5
readme: README.md
authors:
- Rafael Campos <rcampos@altus.cr>
- William Astorga <wastorga@altus.cr>
- Jose Bogarin <jbogarin@altus.cr>
description: Ansible Modules for Cisco ISE
license_file: 'LICENSE'
tags:
- cisco
- ise
- cloud
- collection
- networking
- sdn
dependencies:
  ansible.utils: ">=2.0.0"
repository: https://github.com/CiscoISE/ansible-ise
documentation: https://ciscoise.github.io/ansible-ise/
homepage: https://github.com/CiscoISE/ansible-ise
issues: https://github.com/CiscoISE/ansible-ise/issues
