- name: Check if all nodes are in STANDALONE state
  cisco.ise.personas_check_standalone:
    ip: "{{ item.ip }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"
    hostname: "{{ item.hostname }}"
  loop:
    # ISE PAN Server 1
    - ip: "{{ pan1_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-pan-server-1"
    # ISE PAN Server 2
    - ip: "{{ pan2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-pan-server-2"
    # ISE MNT Server 1
    - ip: "{{ mnt1_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-mnt-server-1"
    # ISE MNT Server 2
    - ip: "{{ mnt2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-mnt-server-2"
    # ISE PSN Server 1
    - ip: "{{ psn1_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-psn-server-1"
    # ISE PSN Server 2
    - ip: "{{ psn2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-psn-server-2"

- name: Export trusted certificates into primary node
  cisco.ise.personas_export_certs:
    primary_ip: "{{ pan1_ip }}"
    primary_username: "{{ ise_username }}"
    primary_password: "{{ ise_password }}"
    name: "{{ item.name }}"
    ip: "{{ item.ip }}"
    hostname: "{{ item.hostname }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"
  loop:
    - name: ISE PAN Server 2
      ip: "{{ pan2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-pan-server-2"
    - name: ISE MNT Server 1
      ip: "{{ mnt1_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-mnt-server-1"
    - name: ISE MNT Server 2
      ip: "{{ mnt2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-mnt-server-2"
    - name: ISE PSN Server 1
      ip: "{{ psn1_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-psn-server-1"
    - name: ISE PSN Server 2
      ip: "{{ psn2_ip }}"
      hostname: "{{ ise_base_hostname | lower }}-psn-server-2"

- name: Promote primary node
  cisco.ise.personas_promote_primary:
    ip: "{{ pan1_ip }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"

- name: Register the nodes to the cluster except the standby MNT
  cisco.ise.personas_register_node:
    primary_ip: "{{ pan1_ip }}"
    primary_username: "{{ ise_username }}"
    primary_password: "{{ ise_password }}"
    fqdn: "{{ item.fqdn }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"
    roles: "{{ item.roles }}"
    services: "{{ item.services }}"
  loop:
    # ISE PAN Server 2
    - fqdn: "{{ ise_base_hostname | lower }}-pan-server-2.{{ ise_domain }}"
      roles:
        - SecondaryAdmin
      services: []
    # ISE MNT Server 1
    - fqdn: "{{ ise_base_hostname | lower }}-mnt-server-1.{{ ise_domain }}"
      roles:
        - PrimaryMonitoring
      services: []
    # ISE PSN Server 1
    - fqdn: "{{ ise_base_hostname | lower }}-psn-server-1.{{ ise_domain }}"
      roles: []
      services:
        - Session
        - Profiler 
    # ISE PSN Server 2
    - fqdn: "{{ ise_base_hostname | lower }}-psn-server-2.{{ ise_domain }}"
      roles: []
      services:
        - Session
        - Profiler

- name: Delete the MNT role from the primary node
  cisco.ise.personas_update_roles_services:
    ip: "{{ pan1_ip }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"
    hostname: "{{ ise_base_hostname | lower }}-pan-server-1"
    roles:
      - PrimaryAdmin
    services: []

- name: Wait for primary application server to come up again 
  pause:
    minutes: 10

- name: Register node 'MNT Server 2' as SecondaryMonitoring
  cisco.ise.personas_register_node:
    primary_ip: "{{ pan1_ip }}"
    primary_username: "{{ ise_username }}"
    primary_password: "{{ ise_password }}"
    fqdn: "{{ item.fqdn }}"
    username: "{{ ise_username }}"
    password: "{{ ise_password }}"
    roles: "{{ item.roles }}"
    services: "{{ item.services }}"
  loop:
    # ISE MNT Server 2
    - fqdn: "{{ ise_base_hostname | lower }}-mnt-server-2.{{ ise_domain }}"
      roles:
        - SecondaryMonitoring
      services: []