- hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:

  - name: Get allowed protocols, skip first one
    cisco.ise.allowed_protocols_info:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      page: 2
      size: 1
    register: result

  - name: Get allowed protocols by name
    cisco.ise.allowed_protocols_info:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      name: "Default Network Access"
    register: result

  - name: Get allowed protocols by id
    cisco.ise.allowed_protocols_info:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      id: "92613980-8c01-11e6-996c-525400b48521"
    register: result
