---
- name: Get Allowed Protocols Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all Allowed Protocols
      cisco.ise.allowedprotocols_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print Allowed Protocols
      ansible.builtin.debug:
        var: result.ise_response

    - name: Get Allowed Protocol by name
      cisco.ise.allowedprotocols_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        name: Default Network Access
      register: result_by_name

    - name: Print Allowed Protocol by Name
      ansible.builtin.debug:
        var: result_by_name.ise_response

