---
- name: Manage Allowed Protocols
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Allowed Protocols
      cisco.ise.allowedprotocols_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: allowed_protocols_list

    - name: Print Allowed Protocols List
      ansible.builtin.debug:
        var: allowed_protocols_list.ise_response

    - name: Create Allowed Protocol
      cisco.ise.allowedprotocols:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: Default Network Access
        description: Default allowed protocols for network access
        processHostLookup: true
        allowPapAscii: false
        allowChap: false
        allowMsChapV1: false
        allowMsChapV2: true
        allowEapMd5: false
        allowLeap: false
        allowEapTls: true
        allowEapTtls: true
        allowEapFast: true
        allowPeap: true
        allowTeap: true
        allowPreferredEapProtocol: true
        preferredEapProtocol: PEAP
        eapTlsLBit: true
        allowWeakCiphersForEap: false
        requireMessageAuth: false
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

