---
- name: Get ANC Policy Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all ANC Policies
      cisco.ise.ancpolicy_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print ANC Policies
      ansible.builtin.debug:
        var: result.ise_response
    - name: Get ANC Policy by name
      cisco.ise.ancpolicy_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        name: Quarantine_Policy
      register: result_by_name

    - name: Print ANC Policy by Name
      ansible.builtin.debug:
        var: result_by_name.ise_response
