---
- name: Update Backup Schedule Configuration
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Update scheduled backup configuration
      cisco.ise.backup_schedule_config_update:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        repositoryName: backup-repo
        backupEncryptionKey: "{{ backup_encryption_key }}"
        frequency: WEEKLY
        time: "03:00"
        status: ENABLE
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

