---
- name: Manage TrustSec Environment Data
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Update TrustSec Environment Data
      cisco.ise.ctsenvdata:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

