---
- name: Rename Custom Attribute
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Rename Custom Attribute
      cisco.ise.custom_attributes_rename:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        currentName: OldAttributeName
        newName: NewAttributeName
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
