---
- name: Manage Custom Attributes
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Custom Attributes
      cisco.ise.custom_attributes_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: custom_attrs

    - name: Print Custom Attributes
      ansible.builtin.debug:
        var: custom_attrs.ise_response

    - name: Create or update Custom Attribute
      cisco.ise.custom_attributes:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        attributeName: Department
        attributeType: STRING
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
