- hosts: ise_servers
  gather_facts: no
  tasks:
  - name: Deploy nodes
    cisco.ise.deployment:
      nodes:
      - name: Node1
        ip: 34.222.49.52
        local_ip: 10.10.1.111
        hostname: ise-server-1
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - PPAN
          - MNT-ACTIVE
          - PDP
      # - name: Node2
      #   ip: 54.190.193.66
      #   local_ip: 10.10.1.5
      #   hostname: ise-server-2
      #   username: admin
      #   password: P@sbg1234
      #   domain: sstcloud.com
      #   roles:
      #     - SPAN
      #     - MNT-STANDBY
      #     - PDP