---
- name: Get all Deployment
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all Deployment
      cisco.ise.deployment_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        timeout: 300
      register: result

    - name: Print deployment info
      ansible.builtin.debug:
        var: result
