- hosts: ise_servers
  gather_facts: no
  vars:
    username: admin
    password: P@sbg1234
    pan1_ip: 34.221.172.205
    pan2_ip: 35.166.253.142
    psn1_ip: 18.237.108.251
    psn2_ip: 54.189.140.230
    pan2_local_ip: 10.10.1.74
    psn1_local_ip: 10.10.1.88
    psn2_local_ip: 10.10.1.198
    domain: sstcloud.com

  tasks:
  - name: Check if all nodes are in STANDALONE state
    cisco.ise.personas_check_standalone:
      name: "{{ item.name }}"
      ip: "{{ item.ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    loop:
      - name: ISE PAN Server 1
        ip: "{{ pan1_ip }}"
      - name: ISE PAN Server 2
        ip: "{{ pan2_ip }}"
      - name: ISE PSN Server 1
        ip: "{{ psn1_ip }}"
      - name: ISE PSN Server 2
        ip: "{{ psn2_ip }}"

  - name: Export trusted certificates into primary node
    cisco.ise.personas_export_certs:
      primary_ip: "{{ pan1_ip }}"
      primary_username: "{{ username }}"
      primary_password: "{{ password }}"
      name: "{{ item.name }}"
      ip: "{{ item.ip }}"
      hostname: "{{ item.hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    loop:
      - name: ISE PAN Server 2
        ip: "{{ pan2_ip }}"
        hostname: ise-pan-server-2
      - name: ISE PSN Server 1
        ip: "{{ psn1_ip }}"
        hostname: ise-psn-server-1
      - name: ISE PSN Server 2
        ip: "{{ psn2_ip }}"
        hostname: ise-psn-server-2

  - name: Promote primary node
    cisco.ise.personas_promote_primary:
      ip: "{{ pan1_ip }}"
      hostname: ise-pan-server-1
      username: "{{ username }}"
      password: "{{ password }}"
      roles:
        - PPAN
        - MNT-ACTIVE

  - name: Wait for primary application server to come up again 
    pause:
      minutes: 10

  - name: Update roles on the rest of the nodes
    cisco.ise.personas_update_roles:
      primary_ip: "{{ pan1_ip }}"
      primary_username: "{{ username }}"
      primary_password: "{{ password }}"
      name: "{{ item.name }}"
      local_ip: "{{ item.local_ip }}"
      hostname: "{{ item.hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      domain: sstcloud.com
      roles: "{{ item.roles }}"
    loop:
      - name: ISE PAN Server 2
        local_ip: "{{ pan2_local_ip }}"
        hostname: ise-pan-server-2
        roles:
          - SPAN
          - MNT-STANDBY
      - name: ISE PSN Server 1
        local_ip: "{{ psn1_local_ip }}"
        hostname: ise-psn-server-1
        roles:
          - PDP
      - name: ISE PSN Server 2
        local_ip: "{{ psn2_local_ip }}"
        hostname: ise-psn-server-2
        roles:
          - PDP