- hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:

  # - name: Get all network policy set
  #   cisco.ise.device_administration_policy_set_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #   register: result

  # - name: Print all
  #   ansible.builtin.debug:
  #     var: result

  # - name: Get a network policy set by id
  #   cisco.ise.device_administration_policy_set_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     id: "acd4b55d-dca3-4b93-a160-8a2d01669827"
  #   register: result

  # - name: Print by id
  #   ansible.builtin.debug:
  #     var: result

  - name: Create or update a network policy set
    cisco.ise.device_administration_policy_set:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      state: present
      default: false
      id: bde8f4d9-a910-4dd4-8735-730b008319e2
      name: New Policy Set 1
      description: New policy set 1
      hitCounts: 0
      rank: 0
      state_: enabled
      condition:
        conditionType: ConditionReference
        isNegate: false
        name: test1
        id: ebae02eb-e430-450f-abd6-03df2564fb7a
        description: New condition for policy set 1
      serviceName: Default Device Admin
      isProxy: false
    register: result

  # - name: Delete a network policy set by id
  #   cisco.ise.device_administration_policy_set:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     state: absent
  #     id: 4f83e8c4-978e-4767-a218-9d5472d4dcc7
  #   register: result