---
- name: Get Duo IdentitySync Sync Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Duo IdentitySync configuration
      cisco.ise.duo_identitysync_sync_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print Duo IdentitySync Info
      ansible.builtin.debug:
        var: result.ise_response

