- hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:

  # - name: Get all
  #   cisco.ise.egress_matrix_cell_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #   register: result

  # - name: Print all
  #   ansible.builtin.debug:
  #     var: result

  # - name: Get by id
  #   cisco.ise.egress_matrix_cell_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     id: d704e911-a916-11eb-8830-2ec507028ea8
  #   register: result

  - name: Create or update an egress_matrix_cell
    cisco.ise.egress_matrix_cell:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      state: present
      name: "Workstations-Printers"
      description: "Updated by import utility (3)."
      sourceSgtId: "bc279f20-a916-11eb-8830-2ec507028ea8"
      destinationSgtId: "bc9ea3e0-a916-11eb-8830-2ec507028ea8"
      matrixCellStatus: "ENABLED"
      defaultRule: "DENY_IP"
    register: result

  - name: Print result
    ansible.builtin.debug:
      var: result