---
- name: Bulk Create Endpoints
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Create multiple endpoints in bulk
      cisco.ise.endpoints_bulk:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        endpoints:
          - mac: "11:22:33:44:55:66"
            groupId: "{{ endpoint_group_id }}"
          - mac: "AA:BB:CC:DD:EE:FF"
            groupId: "{{ endpoint_group_id }}"
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
