- hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:

  # - name: Get all
  #   cisco.ise.filter_policy_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #   register: result

  # - name: Print all
  #   ansible.builtin.debug:
  #     var: result

  # - name: Get by id
  #   cisco.ise.filter_policy_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     id: d704e911-a916-11eb-8830-2ec507028ea8
  #   register: result

  - name: Create or update a filter_policy
    cisco.ise.filter_policy:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      state: present
      subnet: "121.12.10.21/22"
      domains: "default"
      sgt: "Cameras"
      vn: "VN2"
      id: ""
    register: result

  - name: Print result
    ansible.builtin.debug:
      var: result