- hosts: ise_servers
  gather_facts: no
  tasks:

  # - name: Get all
  #   cisco.ise.filter_policy_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #   register: result

  # - name: Print all
  #   ansible.builtin.debug:
  #     var: result

  # - name: Get by id
  #   cisco.ise.filter_policy_info:
  #     ise_hostname: "{{ise_hostname}}"
  #     ise_username: "{{ise_username}}"
  #     ise_password: "{{ise_password}}"
  #     ise_verify: "{{ise_verify}}"
  #     id: d704e911-a916-11eb-8830-2ec507028ea8
  #   register: result

  - name: Get sgt src
    cisco.ise.sgt_info:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      filter: 'name.EQ.Quarantined_Systems'
    register: sgt_src

  - name: Print sgt_src
    ansible.builtin.debug:
      var: sgt_src['ise_response'][0]
    when: not ansible_check_mode

  - name: Create or update a filter_policy
    cisco.ise.filter_policy:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      state: present
      subnet: "121.12.8.0/22"
      domains: "default"
      sgt: "{{sgt_src['ise_response'][0]['name']}}"
      id: ""
    when:
      - sgt_src['ise_response'] is defined
      - sgt_src['ise_response']|length == 1
      - sgt_src['ise_response'][0]['name']
    register: result

  - name: Print result
    ansible.builtin.debug:
      var: result