---
- name: Manage Internal User
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Internal Users
      cisco.ise.internaluser_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: internal_users

    - name: Print Internal Users
      ansible.builtin.debug:
        var: internal_users.ise_response

    - name: Create Internal User
      cisco.ise.internaluser:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: test_user
        password: "{{ user_password }}"
        passwordIDStore: Internal Users
        enablePassword: "{{ user_password }}"
        enabled: true
        email: testuser@example.com
        description: Test internal user
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

