---
- name: Regenerate ISE Root CA
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Regenerate ISE Root CA certificate
      cisco.ise.ise_root_ca_regenerate:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        removeExistingISEIntermediateCSR: false
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

