- hosts: ise_servers
  gather_facts: no
  tasks:
  - name: Deploy nodes
    cisco.ise.deployment:
      nodes:
      - name: ISE PAN Server 1
        ip: 18.236.188.219
        local_ip: 10.10.1.200
        hostname: ise-pan-server-1
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - PPAN
      - name: ISE PAN Server 2
        ip: 54.201.56.80
        local_ip: 10.10.1.233
        hostname: ise-pan-server-2
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - SPAN
      - name: ISE MNT Server 1
        ip: 18.236.94.216
        local_ip: 10.10.1.234
        hostname: ise-mnt-server-1
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - MNT-ACTIVE
      - name: ISE MNT Server 2
        ip: 54.213.43.81
        local_ip: 10.10.1.75
        hostname: ise-mnt-server-2
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - MNT-STANDBY
      - name: ISE PSN Server 1
        ip: 54.212.193.101
        local_ip: 10.10.1.98
        hostname: ise-psn-server-1
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - PDP
      - name: ISE PSN Server 2
        ip: 34.222.6.177
        local_ip: 10.10.1.109
        hostname: ise-psn-server-2
        username: admin
        password: P@sbg1234
        domain: sstcloud.com
        roles:
          - PDP