---
- name: Get LDAP Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all LDAP configurations
      cisco.ise.ldap_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print LDAP Configurations
      ansible.builtin.debug:
        var: result.ise_response
