---
- name: Get MNT Session By MAC Address Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get session by MAC address
      cisco.ise.mnt_session_by_mac_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print Session Info
      ansible.builtin.debug:
        var: result.ise_response
