---
- name: Get MNT Active Session Count Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get active session count
      cisco.ise.mnt_session_active_count_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print Active Session Count
      ansible.builtin.debug:
        var: result.ise_response
