---
- name: Get MNT Account Status Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get account status
      cisco.ise.mnt_account_status_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print Account Status
      ansible.builtin.debug:
        var: result.ise_response
