---
- name: Get MNT Version Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get ISE version information
      cisco.ise.mnt_version_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print Version Info
      ansible.builtin.debug:
        var: result.ise_response
