---
- name: Manage Network Device
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Network Devices
      cisco.ise.networkdevice_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: network_devices

    - name: Print Network Devices
      ansible.builtin.debug:
        var: network_devices.ise_response

    - name: Create Network Device
      cisco.ise.networkdevice:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: Switch_01
        description: Access switch 01
        NetworkDeviceIPList:
          - ipaddress: 192.168.1.10
            mask: 32
        NetworkDeviceGroupList:
          - Device Type#All Device Types
          - Location#All Locations
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
