---
- hosts: ise_servers
  gather_facts: false
  tasks:
    # - name: Get all
    #   cisco.ise.network_access_local_exception_rules_info:
    #     ise_hostname: "{{ ise_hostname }}"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #     policyId: "acd4b55d-dca3-4b93-a160-8a2d01669827"
    #   register: result

    # - name: Print all
    #   ansible.builtin.debug:
    #     var: result

    # - name: Get by id
    #   cisco.ise.network_access_local_exception_rules_info:
    #     ise_hostname: "{{ ise_hostname }}"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #     id: f0a6ce46-17a4-4587-ae55-fefbf3f7c4ff
    #     policyId: "acd4b55d-dca3-4b93-a160-8a2d01669827"
    #   register: result

    - name: Create or update an network_access_local_exception_rules
      cisco.ise.network_access_local_exception_rules:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: absent
        rule:
          default: false
          name: Test2
          hitCounts: 00
          rank: 00
          state: disabled
          condition:
            conditionType: ConditionReference
            isNegate: false
            dictionaryName: Network Access
            attributeName: EapAuthentication
            operator: equals
            attributeValue: EAP-MSCHAPv2
            name: EAP-MSCHAPv2
            id: c456a490-0429-4fd4-91d7-efd1eb1f855a
        profile:
          - PermitAccess
        securityGroup: BYOD
        policyId: acd4b55d-dca3-4b93-a160-8a2d01669827
      register: result

    - name: Print result
      ansible.builtin.debug:
        var: result
