---
- hosts: ise_servers
  gather_facts: false
  tasks:
    # - name: Get all
    #   cisco.ise.network_access_global_exception_rules_info:
    #     ise_hostname: "{{ ise_hostname }}"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #   register: result

    # - name: Print all
    #   ansible.builtin.debug:
    #     var: result

    - name: Get by id
      cisco.ise.network_access_global_exception_rules_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        id: 1353121e-fa90-4cf7-b9cc-a7903e570063
      register: result

    # - name: Create or update an network_access_global_exception_rules
    #   cisco.ise.network_access_global_exception_rules:
    #     ise_hostname: "{{ ise_hostname }}"
    #     ise_username: "{{ ise_username }}"
    #     ise_password: "{{ ise_password }}"
    #     ise_verify: "{{ ise_verify }}"
    #     state: present
    #     rule:
    #       default: false
    #       name: Test2
    #       hitCounts: 0
    #       rank: 0
    #       state: disabled
    #       condition:
    #         conditionType: ConditionReference
    #         isNegate: false
    #         dictionaryName: Network Access
    #         attributeName: EapAuthentication
    #         operator: equals
    #         attributeValue: EAP-MSCHAPv2
    #         name: EAP-MSCHAPv2
    #         id: c456a490-0429-4fd4-91d7-efd1eb1f855a
    #     profile:
    #     - PermitAccess
    #     securityGroup: BYOD
    #   register: result

    - name: Print result
      ansible.builtin.debug:
        var: result
