---
- name: Get Node Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all nodes
      cisco.ise.node_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print Nodes
      ansible.builtin.debug:
        var: result.ise_response
    - name: Get node by name
      cisco.ise.node_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result_by_name

    - name: Print Node by Name
      ansible.builtin.debug:
        var: result_by_name.ise_response
