---
- name: Manage PAN High Availability
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Configure PAN HA
      cisco.ise.pan_ha:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        failedAttempts: 5
        pollingInterval: 300
        primaryHealthCheckNode: "{{ primary_pan_hostname }}"
        secondaryHealthCheckNode: "{{ secondary_pan_hostname }}"
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

