---
- name: Get Proxy Connection Settings Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get proxy connection settings
      cisco.ise.proxy_connection_settings_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: result

    - name: Print Proxy Connection Settings
      ansible.builtin.debug:
        var: result.ise_response
