---
- name: Renew Certificate
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Renew system certificate
      cisco.ise.renew_certificate:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        certType: SYSTEM
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

