---
- name: Manage Repository
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Repositories
      cisco.ise.repository_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: repositories

    - name: Print Repositories
      ansible.builtin.debug:
        var: repositories.ise_response

    - name: Create Repository
      cisco.ise.repository:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: backup-repo
        protocol: SFTP
        serverName: sftp.example.com
        path: /backup
        userName: backup_user
        password: "{{ backup_password }}"
        enablePki: false
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

