---
- name: Manage REST ID Store
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get REST ID Stores
      cisco.ise.restidstore_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: rest_idstores

    - name: Print REST ID Stores
      ansible.builtin.debug:
        var: rest_idstores.ise_response

    - name: Create REST ID Store
      cisco.ise.restidstore:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: External_REST_IDStore
        description: External REST identity store
        ersRestIdStoreAttributes:
          predefinedAttributes: []
          rootUrl: https://api.example.com
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

