---
- name: Get SGT VN VLAN Mapping Information
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get all SGT VN VLAN Mappings
      cisco.ise.sgtvnvlan_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        ise_version: "{{ ise_version }}"
      register: result

    - name: Print SGT VN VLAN Mappings
      ansible.builtin.debug:
        var: result.ise_response
