---
- name: Manage Sponsored Guest Portal
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get Sponsored Guest Portals
      cisco.ise.sponsoredguestportal_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: sponsored_portals

    - name: Print Sponsored Guest Portals
      ansible.builtin.debug:
        var: sponsored_portals.ise_response

    - name: Create or update Sponsored Guest Portal
      cisco.ise.sponsoredguestportal:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: Sponsored_Guest_Portal
        description: Portal for sponsored guest access
        portalType: SPONSORED
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
