---
- name: Stop Replication
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Stop replication to node
      cisco.ise.stop_replication:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        hostname: "{{ target_node_hostname }}"
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result

