---
- name: Manage SXP Local Bindings
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get SXP Local Bindings
      cisco.ise.sxplocalbindings_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: sxp_bindings

    - name: Print SXP Local Bindings
      ansible.builtin.debug:
        var: sxp_bindings.ise_response

    - name: Create SXP Local Binding
      cisco.ise.sxplocalbindings:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        bindingName: IP_SGT_Binding
        ipAddressOrHost: 192.168.1.100
        sgt: 10
        sxpVpn: DEFAULT
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
