---
- name: Manage SXP VPNs
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get SXP VPNs
      cisco.ise.sxpvpns_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
      register: sxp_vpns

    - name: Print SXP VPNs
      ansible.builtin.debug:
        var: sxp_vpns.ise_response

    - name: Create SXP VPN
      cisco.ise.sxpvpns:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        sxpVpnName: Corporate_VPN
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
