---
- name: Manage TACACS Command Sets
  hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: false
  tasks:
    - name: Get TACACS Command Sets
      cisco.ise.tacacscommandsets_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
      register: tacacs_cmdsets

    - name: Print TACACS Command Sets
      ansible.builtin.debug:
        var: tacacs_cmdsets.ise_response

    - name: Create TACACS Command Set
      cisco.ise.tacacscommandsets:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_version: "{{ ise_version }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: Network_Admin_Commands
        description: Commands for network administrators
        permitUnmatched: false
      register: result

    - name: Print Result
      ansible.builtin.debug:
        var: result
